// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.AppView = (function(_super) {
    __extends(AppView, _super);

    function AppView() {
      return AppView.__super__.constructor.apply(this, arguments);
    }

    AppView.prototype.template = _.template($('#gameOverTemplate').html());

    AppView.prototype.initialize = function() {
      this.model.on('change:gameOver', (function(_this) {
        return function() {
          return _this.render();
        };
      })(this));
      return this.newGame();
    };

    AppView.prototype.newGame = function() {
      var gameView;
      this.$el.html('');
      gameView = new GameView({
        model: this.model.get('game')
      });
      return this.$el.append(gameView.$el);
    };

    AppView.prototype.render = function() {
      return this.$el.append(this.template(this.model.toJSON()));
    };

    return AppView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=AppView.map
