// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.AppView = (function(_super) {
    __extends(AppView, _super);

    function AppView() {
      return AppView.__super__.constructor.apply(this, arguments);
    }

    AppView.prototype.template = _.template($('#restartTemplate').html());

    AppView.prototype.templateEndGame = _.template($('#gameOverTemplate').html());

    AppView.prototype.initialize = function() {
      var scoreView;
      this.model.on('gameEnd', (function(_this) {
        return function() {
          _this.render();
          return _this.gameView.disable();
        };
      })(this));
      scoreView = new ScoreView({
        model: this.model
      });
      return this.newGame();
    };

    AppView.prototype.newGame = function() {
      var betSize;
      betSize = +$('.bet').val() || 10;
      this.$el.html('');
      this.model.newGame(betSize);
      this.gameView = new GameView({
        model: this.model.get('game')
      });
      return this.$el.append(this.gameView.$el);
    };

    AppView.prototype.render = function(bankrupt) {
      if (this.model.get('chips') > 0) {
        this.$el.append(this.template(this.model.toJSON()));
        $('.reset-game').on('click', (function(_this) {
          return function() {
            return _this.newGame();
          };
        })(this));
        $('.bet').focus();
        return $('.bet').on('keyup', (function(_this) {
          return function(e) {
            if (e.which === 13) {
              return _this.newGame();
            }
          };
        })(this));
      } else {
        return setTimeout((function(_this) {
          return function() {
            return _this.$el.append(_this.templateEndGame, 1500);
          };
        })(this));
      }
    };

    return AppView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=AppView.map
