// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.DeckView = (function(_super) {
    __extends(DeckView, _super);

    function DeckView() {
      return DeckView.__super__.constructor.apply(this, arguments);
    }

    DeckView.prototype.initialize = function() {
      console.log('creation');
      this.collection.on('change', (function(_this) {
        return function() {
          return _this.render();
        };
      })(this));
      $('.score').append(this.$el);
      return this.render();
    };

    DeckView.prototype.render = function() {
      var cards;
      cards = this.collection.length;
      return this.$el.append($("<div><%= cards %> left</div>"));
    };

    return DeckView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=DeckView.map
