// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ScoreView = (function(_super) {
    __extends(ScoreView, _super);

    function ScoreView() {
      return ScoreView.__super__.constructor.apply(this, arguments);
    }

    ScoreView.prototype.template = _.template($('#scoreTemplate').html());

    ScoreView.prototype.initialize = function() {
      this.model.on('change', (function(_this) {
        return function() {
          return _this.render();
        };
      })(this));
      this.render();
      return $('body').prepend(this.$el);
    };

    ScoreView.prototype.render = function() {
      this.$el.html('');
      return this.$el.append(this.template(this.model.toJSON()));
    };

    return ScoreView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=ScoreView.map
