// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = (function(_super) {
    __extends(App, _super);

    function App() {
      return App.__super__.constructor.apply(this, arguments);
    }

    App.prototype.initialize = function() {
      this.set('playerWins', 0);
      this.set('dealerWins', 0);
      return this.newGame();
    };

    App.prototype.newGame = function() {
      var game;
      this.set('game', game = new Game());
      return this.get('game').on('gameEnd', (function(_this) {
        return function() {
          return _this.updateScore();
        };
      })(this));
    };

    App.prototype.updateScore = function() {
      var playerWins;
      playerWins = this.get('game').get('playerWins');
      if (playerWins) {
        this.set('playerWins', this.get('playerWins') + 1);
      } else if (playerWins === false) {
        this.set('dealerWins', this.get('dealerWins') + 1);
      }
      console.log(this.get('playerWins'));
      return this.set('gameEnd', this.get('game').get('gameOverMessage'));
    };

    return App;

  })(Backbone.Model);

}).call(this);

//# sourceMappingURL=App.map
