// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.DealerHand = (function(_super) {
    __extends(DealerHand, _super);

    function DealerHand() {
      return DealerHand.__super__.constructor.apply(this, arguments);
    }

    DealerHand.prototype.isDealer = true;

    DealerHand.prototype.play = function() {
      this.each((function(card) {
        if (!card.get('revealed')) {
          return card.flip();
        }
      }));
      while (!(this.score() >= 17)) {
        this.hit();
      }
      return this.stand();
    };

    return DealerHand;

  })(Hand);

}).call(this);

//# sourceMappingURL=DealerHand.map
